In [0]:
import numpy as np
import tensorflow as tf

In [2]:
#Check tf version
print(tf.__version__)

1.13.0-rc0


In [0]:
np.random.seed(42)
tf.set_random_seed(42)

In [5]:
rand_a = np.random.uniform(0, 100, (5,5))
rand_a

array([[37.45401188, 95.07143064, 73.19939418, 59.86584842, 15.60186404],
       [15.59945203,  5.80836122, 86.61761458, 60.11150117, 70.80725778],
       [ 2.05844943, 96.99098522, 83.24426408, 21.23391107, 18.18249672],
       [18.34045099, 30.4242243 , 52.47564316, 43.19450186, 29.12291402],
       [61.18528947, 13.94938607, 29.21446485, 36.63618433, 45.60699842]])

In [6]:
rand_b = np.random.uniform(0, 100, (5,1))
rand_b

array([[78.51759614],
       [19.96737822],
       [51.42344384],
       [59.24145689],
       [ 4.64504127]])

In [0]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [0]:
add_op = a + b
mul_op = a * b

In [12]:
# Just heating up with tf.session and placeholders
with tf.Session() as sess:
  
  add_result = sess.run(add_op, feed_dict={a:rand_a, b:rand_b})
  print(add_result)
  
  mul_result = sess.run(mul_op, feed_dict={a:rand_a, b:rand_b})
  print(mul_result)
  
  

[[115.9716   173.58902  151.71698  138.38344   94.11946 ]
 [ 35.56683   25.77574  106.58499   80.07888   90.774635]
 [ 53.48189  148.41443  134.66771   72.65736   69.60594 ]
 [ 77.58191   89.66568  111.7171   102.43596   88.364365]
 [ 65.83033   18.594427  33.859505  41.281227  50.25204 ]]
[[2940.7988   7464.7803   5747.4404   4700.5225   1225.0208  ]
 [ 311.48016   115.977745 1729.5267   1200.269    1413.8353  ]
 [ 105.85256  4987.6104   4280.7065   1091.9208    935.0066  ]
 [1086.515    1802.3754   3108.7334   2558.905    1725.2838  ]
 [ 284.20822    64.79547   135.7024    170.17659   211.8464  ]]


In [0]:
# Now we will buid a Neural Network

In [0]:
n_features = 10
n_dense_neurons = 3

In [0]:
x = tf.placeholder(tf.float32, (None, n_features))
W = tf.Variable(tf.random_normal([n_features, n_dense_neurons]))
b = tf.Variable(tf.ones([n_dense_neurons]))

In [0]:
# We want to do y = Wx + b

In [0]:
y = tf.matmul(x, W)

In [0]:
z = tf.add(y, b)

In [0]:
# Activation function
a = tf.sigmoid(z)

In [0]:
init = tf.global_variables_initializer()

In [0]:
with tf.Session() as sess:
  
  sess.run(init)
  
  layer_out = sess.run(a, feed_dict={x: np.random.random([1, n_features])})

In [27]:
print(layer_out)

[[0.6671997  0.5886109  0.75623775]]


In [0]:
# Notice this was just a feed forward